[package]
authors = ["Alexander Morozov <rust@meltdown.ru>"]
name = "decimate"
version = "0.1.0"

[dependencies]
num = "0.1"
rustc-serialize = { optional = true, version = "~0.3" }

[features]
default = ["rustc-serialize"]
